*
BRKTRC RMB    1	       1=>P-COUNTER IS AT BREAKPOINT
*                      AND USER WANTS TO CONTINUE-
*                      ONE TRACE WILL BE DONE AND
*                      BREAKPOINT RESTORED
ENDIN0 EQU    $A080    END OF VAR'S INTZ'D to 0
*
ACIAT  RMB    1        SAVE ACIS CONTROL REG FOR
*                      CONTROL LOOP INITIALIZE
*  EXORTAPE RAM
*AUXILIARY REGISTER STORAGE
FIDH   RMB    1
FIDL   RMB    1
STARTP RMB    1
STOPPG RMB    1
TOTCNT RMB    1        WINDOW WIDTH
PATDEL RMB    1        PATTERN-ELEMENT LENGTH
CL     RMB    1        CHECK/LOAD SUB
CLL    RMB    1
CLLL   RMB    1        RTS
*TAPE TEMPORARIES
H      RMB    1        LOAD IX, ETC.
L      RMB    1
Q      RMB    1        Q HOLDS LAST BYTE RECOVERED
R      RMB    1        R,S IS CRC REGISTER
S      RMB    1
V      RMB    1        PAGE COUNT
T1     EQU    CL
*
* REST OF 128 RAM IS USED FOR STACK
*
       RMB    36
STACK  RMB    1        START OF STACK AREA
