*
*         AUDIO HARDWARE SPECIFICATIONS
* OUTPUT FROM PIA B2 THROUGH 11:1 VOLTAGE DIVIDER
*    (4.7K, 470) INTO MIKE JACK
* INPUT FROM SPKR JACK, THROUGH DC-RESTORING
*    CIRCUIT AND SCHMIDTT TRIGGER
*    (MC14583 PREFERRED) INTO PIA B0
*  RECOVERED PULSE PHASE MATTERS, SO USE SWITCH TO
*     SELECT PHASE -- BOTH AVAILABLE FROM MC14583
