*
* SWI-1 SOFTWARE INTERRUPT LEVEL 1 PROCESSING
*
SWI15  EQU    *
       STS    SP       SAVE USER'S SP
*
       LDAA   #3
       JSR    BRKSUB   GO TAKE OUT ALL THE BREAKS
*
* DECREMENT P-COUNTER
*
       TSX             X:=STACK POINTER - 1
       TST    6,X      IF LOWER BYTE = 0 => BORROW
       BNE    SWI151   BRANCH IF BORROW NOT REQ'D
       DEC    5,X      DECREMENT UPPER BYTE
SWI151 DEC    6,X      DECREMENT LOWER BYTE
*
* TEST FOR ADDRESS TRACE OR BREAK
*
       LDX    5,X      X:=P COUNTER
       CPX    TRCADR   IS SWI FOR TRACE?
       BEQ    TRCINH   YES, GO TO TRACE INT HANDLER
*
       LDAA   0,X      GET INSTRUCTION CAUSING SWI
       CMPA   #SWI     WAS IT REPLACED BY CALL TO BREAK
       BNE    BRKINH   YES, SO MUST BE A BREAK
*
* USER SWI-TRANSFER THROUGH LEVEL 2 SWI
*
       TSX             X:=STACK POINTER
       INC    6,X      UPDATE LOW BYTE OF P-COUNTER
       BNE    INCNOV   BRANCH IF NO CARRY
       INC    5,X      UPDATE HIGH BYTE IF NECESSARY
INCNOV LDX    SWI2     X:=POINTER TO LEVEL 2 SWI HANDLER
       JMP    0,X      GO TO LEVEL 2 HANDLER
*
*
*
*
* BREAK INTERRUPT HANDLER
*
BRKINH EQU    *
       JSR    PRINT    STOP AND SHOW REGS TO USER
CTRL   JMP    CONTRL   RETURN TO CONTROL LOOP
