*
* SENCRC SENDS THE CRC REGISTERS TO TAPE
*
*
*     RAM:  R, S (FREED AFTER THIS); L (SCRATCH)
*     REGS:  ACCA, ACCB (DESTROYED)
*
SENCRC LDAA   S
       STAA   L        TEMPORARY CRC(L) STORAGE
       LDAA   R
       BSR    BYTOV1   SEND CRC(H)
       LDAA   L
       BRA    BYTOV1   SEND CRC(L)
*
* MASTERDUMP SENDS A COMPLETE FILE TO TAPE:
*     HEADERECORE, DUMPAGERECORDS (1-256), TRAILERECORD
*
*     RAM: STARTP, STOPPG (UNMODIFIED)
*          H, L (TEMP)
*     REGS: NEW EVERYTHING
*
MASTER BSR    DSETUP   SETUP DUMP PORT
       BSR    HEADER   SEND HEADERECORD
       LDAA   STARTP   GET STARTPAGE
       STAA   H        PRESENT PAGE
       DEC    H
MAST1  INC    H
       BSR    DUMPAG
       LDAA   TTY
       ANDA   #$7F
       CMPA   #ESC
       BEQ    MAST3
       LDAB   STOPPG   GET STOPAGE
       CMPB   H        PRESENT PAGE
       BNE    MAST1    BRANCH IF NOT DONE
MAST3  BSR    TRAILR   SEND TRAILERECORD
MAST2  RTS
SETUP  CLR    TACON    INTO DATA DIRECTION REG.
       LDAA   #$04     B2 AN OUTPUT, REST INPUTS
       STAA   TP       (ONLY B0 USED FOR INPUT)
       STAA   TACON    BACK TO DATA REGISTER
       RTS
