*
*
* RAM - LOCATIONS DEVOTED TO VARIABLE INFORMATION
*
*
       ORG    $A000    START OF RAM .
NBRBPT EQU    8        # OF BREAKPOINTS SUPPORTED
*
* THE FOLLOWING ARE INITIALIZED AT START
*
IOV    RMB    2        I/O INTERRUPT POINTER
BEGA   RMB    2        BEGIN ADDRESS PRINT/PUNCH
ENDA   RMB    2        END ADDRESS PRINT/PUNCH
NIO    RMB    2        NMI INTERRUPT POINTER
SP     RMB    2        USER STACK POINTER
SWI1   RMB    2        LEVEL 1 SWI VECTOR
SWI2   RMB    2        LEVEL 2 SWI VECTOR
BRINS  RMB    8        STORAGE FOR CONDITIONAL BRANCH
*                            ROUTINE
BRANEN EQU    *        END OF BRANCH ROUTINE + 1
*
* THE FOLLOWING ARE INITIALIZED TO ZERO AT START
*
*
OUTSW  RMB    1        OUTPUT SWITCH
*                       (ZERO => ECHO INPUT)
TRCADR RMB    2        TRACE ADDRESS
TRCINS RMB    1        OP CODE REPLACED BY SWI
NTRACE RMB    2        NO. OF INSTRUCTIONS TO TRACE
*
BRKADR RMB    NBRBPT*2 BREAKPOINT ADDRESS TABLE
BRKINS RMB    NBRBPT*2 OP CODES FOR BREAK REPLACEMENT
*                            (UPPER BYTE OF EACH
*                             PAIR USED ONLY)
CKSM   EQU    *        CHECKSUM
ASAVE  EQU    *        A REG SAVE
TEMP   EQU    *        CHAR COUNT(INADD)
       RMB    1
*
*
BYTECT EQU    *        BYTE COUNT
MCONT  EQU    *        TMP
       RMB    1
*
*
XHI    RMB    1        X REG HIGH (TEMP)
XLOW   RMB    1        X REG LOW
*
*
SSAVE  EQU    *        S REG SAVE
TW     EQU    *        TEMP DOUBLE BYTE
       RMB    2
*
*
BRKSIN RMB    1        1=>BREAKS ARE IN USER PROGRAM
