*
* INSTRUCTION TO BE TRACED IS NOT A BRANCH
*
CKOBRA LDX    TRCADR   X : = TRACE ADDRESS
       LDAB   0,X      GET INSTR TO BE TRACED
       CMPB   #$6E     IS IT A JUMP, INDEXED?
       BEQ    JMPIDX   YES, GO SIMULATE JUMP IDXED
       CMPB   #$7E     JUMP, EXTENDED?
       BEQ    JMPEXT
       CMPB   #$AD     JSR,  INDEXED?
       BEQ    JMPIDX   ( JUMP IDXED IS SAME AS
*                       TRANSFER OF CONTROL )
       CMPB   #$BD     JSR, EXTENDED?
       BEQ    JMPEXT
       CMPB   #$3B     RTI?
       BEQ    RTISIM
       CMPB   #$39     RTS?
       BEQ    RTSSIM
       CMPB   #$8D     BSR?
       BEQ    BRGO     ( BRANCH PROCESSING )
*
* NOT A BRANCH, JUMP. RTI, RTS
* A REGISTER HOLDS # BYTES IN INSTRUCTION
*
       BRA    BRG1     PUT IN NEW SWI AND
*                            TRACE NEXT INSTRUCTION
*
* JUMP, JSR INDEXED SIMULATION
*
JMPIDX LDAA   1,X      A : = ADDRESS OFFSET
       TSX
       LDX    3,X      GET TARGETS X REG
       BRA    BRG1     UPDATE X, TRACE NEXT INSTR
*
* JUMP,  JSR EXTENDED
*
JMPEXT LDX    1,X      GET ADDRESS TO BE JUMPED TO
       BRA    BRG2     GO TRACE NEXT INSTR.
*
* RTI ENCOUNTERED
*
RTISIM TSX
       LDX    12,X     GET P-COUNTER FROM STACK
       BRA    BRG2     GO TRACE NEXT INSTR.
*
* RTS ENCOUNTERED
*
RTSSIM TSX
       LDX    7,X      GET RETURN P-REG FROM STACK
       BRA    BRG2     GO TRACE NEXT INSTR
