       BEQ    INZ
       LDAA   #$15
       BRA    INZ1     SET 2 STOP BITS
*
*
BADDRJ JMP    BADDR    GO BUILD ADDRESS
*
*
* RESET ALL BREAKPOINTS
*
DELBRK LDAA   #1       RESET BREAKS FLAG
BSRBRK BSR    BRKSUB   BREAK HANDLING SUBR.
       BRA    CNTRL2   RETURN TO COMMAND LEVEL
*
* RESET 1 BREAKPOINT
*
RSTBRK BSR    BADDRJ   PUTS USER ENTERED ADDRESS
*                            INTO XHI,XLO
       CLRA            RESET 1 BREAK FLAG
       BRA    BSRBRK   GO RESET 1
*
* PRINT OUT ALL NON-ZERO BREAK ADDRESSES
*
PNTBRK JSR    PCRLF    DO CR/LF
       LDAA   #2       PRINT BREAK ADDRESSES FLAGS
       BRA    BSRBRK   GO PRINT
*
* SET ONE BREAK
*
SETBRK BSR    BADDRJ   GET USER ENTERED ADDRESS (XHI,XLO)
       LDAA   #4       SET ONE BREAK FLAG
       BSR    BRKSUB   GO SET IT
       BRA    PNTBRK   PRINT ALL BREAKPOINTS
