OUTCH1 PSHB            SAVE BREG
OUTC1  LDAB   ACIAS
       ASRB
       ASRB
       BCC    OUTC1    XMIT NOT READY
       STAA   ACIAD    OUTPUT CHAR
       PULB
       RTS
*
* INPUT ONE CHAR TO AREG
INCH1  LDAA   ACIAS
       ASRA
       BCC    INCH1    RECEIVER NOT READY
       LDAA   ACIAD    INPUT CHAR
       ANDA   #$7F     RESET PARITY BIT
       CMPA   #$7F
       BEQ    INCH1    RUBOUT;DEL
       TST    OUTSW    SHOULD INPUT BE ECHOED?
       BEQ    OUTCH1   IF SO, OUTPUT THE CHAR
       RTS             ELSE,RETURN TO CALLER OF INCH1
*
* CONSTANT INITIALIZATION
* S = POINTER TO ROM BYTES TO BE COPIED TO RAM
* X = POINTER TO RAM BYTES TO BE INITIALIZED
*
START  EQU    *        ACTUAL CODE START
       LDS    #ADRSTR-1 START OF CONSTANT DATA
       LDX    #SP      START OF RAM AREA
*
INILP1 PULA            GET NEXT CONSTANT BYTE
       STAA   0,X      INIT NEXT RAM BYTE
       INX             UPDATE POINTER
       CPX    #BRANEN  END OF CONSTANT RAM AREA?
       BNE    INILP1   NO, CONTINUE INITIALIZATION
*
* INITIALIZATION TO 0
* X HOLDS INDEX OF 1ST BYTE TO BE SET TO 0
*
INILP2 CLR    0,X      CLEAR NEXT BYTE OF RAM
       INX             UPDATE INDEX
       CPX    #ENDIN0  ANY MORE BYTES TO INIT?
       BNE    INILP2   NO, CONTINUE CLEARING
*
* SET CC SO WHEN WE 'GO' TO USER PGM THE 
*   INTERRUPT MASK IS SET
*
       LDAA   #$D0
       STAA   $A079    PUT IN STACK TO BE PULLED
*
* INITIALIZE ACIA
*
       LDAA   #3       MASTER RESET CODE
       STAA   ACIAS    RESET ACIA
*
INZ    LDAA   #%00010001 CHAR LEN=8; NO PARITY
*                          2 STOP BITS
*
INZ1   STAA   ACIAT    SAVE FOR CONTROL LOOP ACIA IN
