LOADV  BRA    LOAD2
CHECK  LDAA   #$01     INSERT CHECK COMMAND
       BRA    C12
LOAD2  LDAA   #$E7     INSERT LOAD COMMAND
       STAA   CL       (STORE B INDEXED)
       CLR    CLL      NOP/ZERO DISPLACEMENT
       LDAA   #$39     INSERT RTS
       STAA   CLLL
* FALL INTO GETLOAD
*
* GETLOAD SEARCHES FOR THE DESIRED FILE,
*     THEN LOADS IT INTO RAM
*
*     RAM:  Q, R, S, H, L (SCRATCH)
*           TOTCNT, FIDH, FIDL (PERM)
*
GETLOA JSR    LSETUP   SET UP PIA
       BSR    GETFIL   SEARCH FOR CORRECT FILE
       BEQ    GET4     OUT IFF ESCAPED
GET2   BSR    STARTV   GET THE NEXT RECORD-TYPE
       BEQ    GET4     OUT IF ESCAPE
       CMPB   #$20     TRAILERECORD?
       BEQ    GET1
       CMPB   #$10     DUMPAGERECORD?
       BNE    GET2
       BSR    DUMPR    BRING IT IN!
       BEQ    GET4     OUT IFF ESCAPE
       BRA    GET2
GET1   TST    V        CHECK PAGE COUNT
       BEQ    GET4
       BMI    GET3
       LDAA   #'-      '-' FOR MISSING PAGE(S)
       BRA    GET5
GET3   LDAA   #'+      '+' FOR EXTRA PAGE(S)
GET5   JSR    OUTCH    PRINT IT!
GET4   RTS             RETURN
