*
***********************
*
* SIGNED MULTIPLY -----
*
*     THIS ROUTINE MULTIPLIES THE TWO SIGNED NUMBERS IN
*     THE A AND B REGISTERS AND PUTS THE SIGNED
*     16 BIT ANSWER IN THE CONCATENATED A:B WHERE
*     THE A REGISTER IS THE MSB. THIS ROUTINE DESTROYS
*     THE CALLER'S X-REGISTER.
*
*     DURING EXECUTION THE STACK CONTAINS:
*     0,X  =  FLAG
*
*     THE ROUTINE IS PURE,RE-ENTRANT AND POSITION INDEPENDENT.
*
*     THE METHOD USE EVALUATES EACH ARGUMENT AND IF IT
*     IS NEGATIVE IT IS 2'S COMPLEMENTED AND THE FLAG IS
*     INCREMENTED. IF AFTER EVALUATING BOTH ARGUMENTS THE
*     FLAG IS EVEN (0 OR 2) THEN THE ANSWER WILL BE POSITIVE,
*     ELSE,THE ANSWER WILL NEED TO BE 2'S COMPLEMENTED.
*     UNSIGNED MULTIPLE ROUTINE IS USED TO MULTIPLY THE
*     CORRECTED REGISTERS
*
*    AVERAGE EXECUTIONS TIMES:
*     A-REG  B-REG
*      +      +           268 AVERAGE
*      +      -           283 AVERAGE
*      -      +           283 AVERAGE
*      -      -           286 AVERAGE
*
*
*************************
*
SMUL   DES             CARVE OUT A PLACE ON THE STACK F...
       TSX             GET POINTER TO THAT PLACE
       CLR    0,X      CLEAR FLAG
       TSTA            CHECK MULTIPLIER
       BPL    SML1     POSITIVE, NO COMP. NEEDED
       NEGA            2'S COMP. ARGUMENT
       INC    0,X      INCR FLAG
SML1   TSTB            TEST OTHER ARG
       BPL    SML2     NO COMP NEEDED
       NEGB
       INC    0,X      INCR FLAG
SML2   BSR    MUL      GO DO UNSIGNED MULTIPLY
       TSX             GET BACK PTR TO FLAG
       ROR    0,X      SEE IF FLAG IS EVEN OR ODD
       BCC    SML3     EVEN ANSWER IS OKAY 'CAUSE ITS F...
       NEGA            DBL PRECISION 2'S COMP
       NEGB
       SBCA   #0
SML3   INS             CLEANUP STACK
       RTS             RETURN TO CALLER
