*
* GO TO REQUESTED
*
GOTO   BSR    BADDRJ   GO GET ADDRESS FROM USER
*                      XHI,XLOW HOLD ADDRESS
       LDAA   #$FF     FLAG FOR PUTTING IN BREAKS
       BSR    BRKSUB   GO PUT IN BREAKS
       TSX
       LDAA   XHI      SAVE PCH ON STACK
       STAA   5,X
       LDAA   XLOW     PUSH PCL
       STAA   6,X
       RTI             GO TO USER PRG
*
* SINGLE INSTRUCTION TRACE REQUESTED
*
NEXT   LDX    #1       # INSTRUCTIONS TO TRACE
TRACE2 CLR    BRKTRC   CLEAR FLAG INDICATING TRACE
*                      IS DUE TO BREAK
TRACE3 STX    NTRACE   SAVE # INST'S TO TRACE
*                            IS DUE TO BREAK
       LDX    SP       X : = STACK POINTER
       LDX    6,X      X : = ADDRESS OF INSTR TO BE EX
       STX    TRCADR   SAVE IN TRACE ADDRESS STORE
       LDAA   0,X      GET INSTRUCTION TO BE TRACED
       STAA   TRCINS   SAVE IN TRACE INSTRUCTION STORE
       JMP    CONTRC   GO TO CONTINUE TRACE PART OF
*
* MULTIPLE INSTRUCTION TRACE
*
TRACE  BSR    BADDRJ   GET # OF INSTRUCTION TO TRACE
       BRA    TRACE2   GO TRACE'M
*
* CONTINUE EXECUTION
*
CONT   INC    BRKTRC   TRACE 1 TO RESTORE SWI'S
       LDX    #1       ONE TRACE ONLY
       BRA    TRACE3
*
*
* R COMMAND
*
* PRINT STACK CONTENTS
*
PSTAK1 JSR    PCRLF    PRINT CR LF
       LDX    #MCL3    PRINT HEADER
       JSR    PDATA1
PSTAK  BSR    PRINT    PRINT STACK
CNTRL2 JMP    CONTRL   RETURN TO COMMAND LEVEL
