* IS IN (NOT SWI).
* IF ADDRESS = XHI,XLO THEN SET ADDRESS = 0
FNDRPL LDAA   0,X      GET TOP BYTE OF ADDRESS
       CMPA   XHI      DO TOP BYTES COMPARE
       BNE    BKCON2   NO,CONTINUE LOOP
       LDAB   1,X      GET LOW BYTE OF ADDR
       CMPB   XLOW     SAME FOR LOW BYTES
       BNE    BKCON2
*
CLRBRK CLR    0,X      CLEAR OUT BREAK
       CLR    1,X      ADDRESS FIELD
       BRA    BKCON2   CONTINUE LOOP
*
*
OT2HS  JMP    OUT2HS
OT4HS  JMP    OUT4HS
*
*
* PRINT OUT BREAK ADDRESS
* FUNCTION = 2, BREAK ADDRESS NOT = 0, X = ADDRESS IN
*
PRNTBK LDS    SSAVE
       BSR    OT4HS    OUTPUT ADDRESS AND SPACE
       BRA    BKCON3   OUT4HS INCREMENTS X,
*                      SO BYPAS 2 INX'S
