*
* GETFILE LOOKS FOR:
*     1)  A START SEQUENCE
*     2)  A HEADERECORD TYPE
*     3)  A FILE ID MATCH WITH FIDH, FIDL
* AND RETURNS WHEN FOUND, OR ESCAPED
*
*     REGS:  ACCA, ACCB (SCRATCH ONLY)
*
G1     LDAA   #'X      INDICATE WRONG FILE FOUND
       BSR    CRCK2    SEND CHAR TO TTY
GETFIL BSR    STARTF
       BEQ    G2       OUT IFF ESCAPE
       CMPB   #$08     HEADERECORD-TYPE?
       BNE    GETFIL   BRANCH IF NOT
       BSR    LDV      GET BYTE IN ACCB
       CMPB   FIDH     GOOD FILE ID(H)?
       BNE    G1
       BSR    LDV
       CMPB   FIDL     GOOD FILE ID(L)?
       BNE    G1
       LDAA   #'H      INDICATE HEADER FOUND
       BSR    CRCK2
       BSR    LDV
       STAB   V        STORE PAGE COUNT
G2     RTS
*
* STARTFIND LOOKS FOR THE 16-BIT START SEQUENCE 89AF
*     RETURNS WITH THE NEXT BYTE, THE RECORD TYPE,
*     IN Q AND ACCB.
*
*     RAM:  Q, R, S, TOTCNT (PERM), H (SCRATCH)
*     REGS:  ACCA, ACCB (SCRATCH ONLY)
*     EXIT:  FALLS INTO LOADBYTE, WHICH
*            FALLS INTO LOADBIT, WHICH
*            FALLS INTO CRC
*     ESCAPE:  ESC IN COMMAND PORT GETS OUT
*                (TEST DONE IN CRC)
*
STARTF CLR    H        ACCUMULATES 16 BITS
       CLR    Q
STA1   ASL    Q        SHIFT THE 16-BIT REGISTER
       ROL    H
       BSR    LOADB1
       BEQ    G2       OUT IFF ESCAPED
       LDAA   H
       LDAB   Q
       CMPA   #$89     START SEQUENCE
       BNE    STA1
       CMPB   #$AF
       BNE    STA1
STA2   CLR    R        CLEAR THE CRC REGISTER
       CLR    S
* FALL INTO LOADBYTE TO RETURN A BYTE
