*
       STAA   ACIAS    INZ ACIA
ENT1   LDS    SP
       JSR    PCRLF
       BRA    CONTB    SKIP TO INSURE MIKBUG : COMPAT.
INCH2  BRA    INCH1    MIKBUG 1.0 INPUT 1 CHARACTER
CONTB  LDX    #MCL2    PRINT HEADER
       JSR    PDATA1   PRINT DATA STRING
       LDX    #NMI     INIT PDN
       STX    NIO
