*
* TRACE INTERRUPT HANDLER
* P-COUNTER  HAS BEEN DECREMENTED TO POINT AT SWI
* TRCINS HOLDS OP CODE REPLACED BY SWI
* X HOLD ADDRESS WHERE TRACE SWI IS
*
TRCINH LDAA   TRCINS   GET OP CODE OF TRACED INSTR
       STAA   0,X      RESTORE TO USER'S CODE
*
       TST    BRKTRC   IS PROCESSING TO BE
*                           IMMEDIATELY CONTINUED?
       BEQ    NBKTRC   BRANCH IF NOT
*
* PROCESSING IS TO 'CONTINUE'
*
       CLR    BRKTRC   RESET CONTINUE FLAG
       LDAA   #$FF     FLAG TO SET BREAKS IN CODE
       JSR    BRKSUB   PUT BREAKS IN
       CLR    TRCADR   NO MORE TRACE, SO CLEAR ADDRESS
       CLR    TRCADR+1
       RTI             CONTINUE
*
* TRACE IS DUE TO N OR T TRACE COMMANDS
*
NBKTRC JSR    PRINT    PRINT STACK
       LDX    NTRACE   GET # INSTRUCTIONS TO TRACE
       DEX             DECREMENT COUNT
       STX    NTRACE   AND RESTORE
       BEQ    CTRL     BRANCH IF ALL TRACES DONE
*
* TRACE NOT DONE - TRACE NEXT INSTRUCTION
*
CONTRC LDAA   TRCINS   GET CURRENT INSTRUCTION
       STAA   BRINS    SAVE IN CASE IT'S A BRANCH
       BSR    OPCBYT   GO GET # BYTES/TYPE
       TSTA            CHECK FOR BRANCH
       BPL    CKOBRA   CHECK FOR OTHER THAN BRANCH
